flowchart TD
    subgraph PENGGUNA [PENGGUNA]
        direction TB
        start((start))
        A[membuka halaman reservasi]
        D[menginput data meja, tanggal, \nwaktu, tamu, catatan]
        E[mengklik Konfirmasi Reservasi]
        F{Data\nKosong?}
    end

    subgraph SISTEM [SISTEM]
        direction TB
        B[mengambil data meja]
        C[menampilkan daftar meja]
        G[menampilkan pesan error]
        H[memproses pesanan/reservasi]
        I{Berhasil?}
        J[pesan error]
        K[membersihkan keranjang]
        L[mengarahkan ke pembayaran]
        finish((end))
    end

    start --> A
    A -->| | B
    B --> C
    C -->| | D
    D --> E
    E --> F
    F -- iya --> G
    G -->| | D
    F -- tidak --> H
    H --> I
    I -- tidak --> J
    J -->| | D
    I -- iya --> K
    K --> L
    L --> finish

    classDef default fill:#fff,stroke:#333,stroke-width:2px;
    classDef startEnd fill:#000,stroke:#000,color:#fff,font-weight:bold;
    class start,finish startEnd;
