-- Update Image URLs to match Local XAMPP
UPDATE menu_items SET image_url = '/gambar/menu1.jpeg' WHERE name = 'Suki Mix Platter';
UPDATE menu_items SET image_url = '/gambar/menu2.jpeg' WHERE name = 'Seafood Suki Set';
UPDATE menu_items SET image_url = '/gambar/menu3.jpeg' WHERE name = 'Premium Suki Selection';
UPDATE menu_items SET image_url = '/gambar/menu4.jpeg' WHERE name = 'Beef Teriyaki';
UPDATE menu_items SET image_url = '/gambar/menu5.jpeg' WHERE name = 'Chicken Katsu';
UPDATE menu_items SET image_url = '/gambar/menu6.jpeg' WHERE name = 'Chicken Tulip';
UPDATE menu_items SET image_url = '/gambar/menu7.jpeg' WHERE name = 'Beef Yakiniku Set';
UPDATE menu_items SET image_url = '/gambar/menu10.jpeg' WHERE name = 'Ayam Geprek Nasi Daun Jeruk';
UPDATE menu_items SET image_url = '/gambar/slide3.jpeg' WHERE name = 'Beef Enoki Roll Bowl';
UPDATE menu_items SET image_url = '/gambar/menu13.jpeg' WHERE name = 'Ayam Bakar Sambal Rempah';
UPDATE menu_items SET image_url = '/gambar/menu14.jpeg' WHERE name = 'Chicken Crispy Rice Bowl';
UPDATE menu_items SET image_url = '/gambar/menu16.jpeg' WHERE name = 'Chicken Katsu Bento Box';
UPDATE menu_items SET image_url = '/gambar/menu17.jpeg' WHERE name = 'Bento Ayam Saos Pedas';
UPDATE menu_items SET image_url = '/gambar/menu18.jpeg' WHERE name = 'Ayam Crispy Wijen Bowl';
UPDATE menu_items SET image_url = '/gambar/menu19.jpeg' WHERE name = 'Bento Dimsum Combo';
UPDATE menu_items SET image_url = '/gambar/menu8.jpeg' WHERE name = 'Sate Suki (SMA)';
UPDATE menu_items SET image_url = '/gambar/menu15.jpeg' WHERE name = 'Beef Pastry Roll';
UPDATE menu_items SET image_url = '/gambar/minum1.jpeg' WHERE name = 'Matcha Latte Ice';
UPDATE menu_items SET image_url = '/gambar/minum2.jpeg' WHERE name = 'Nanas Squash';
UPDATE menu_items SET image_url = '/gambar/slide1.jpg' WHERE name = 'Gyudon Signature Bowl';
UPDATE menu_items SET image_url = '/gambar/slide2.jpeg' WHERE name = 'Grill & Suki Set';
UPDATE menu_items SET image_url = '/gambar/slide4.jpeg' WHERE name = 'Beef Yakiniku Bento';
UPDATE menu_items SET image_url = '/gambar/paket1.jpeg' WHERE name = 'Paket Ulang Tahun';
UPDATE menu_items SET image_url = '/gambar/paket2.jpeg' WHERE name = 'Promo Paket Valentine';
UPDATE menu_items SET image_url = '/images/paket_grill_berdua.png' WHERE name = 'Paket Grill Berdua (Hemat)';
UPDATE menu_items SET image_url = '/gambar/paket4.jpeg' WHERE name = 'Paket Grill Koncoan';
UPDATE menu_items SET image_url = '/gambar/paket5.jpeg' WHERE name = 'Paket Merdeka';
UPDATE menu_items SET image_url = '/gambar/paket6.jpeg' WHERE name = 'Oktober Seru';
UPDATE menu_items SET image_url = '/gambar/paket7.jpeg' WHERE name = 'Oktober Megah';
UPDATE menu_items SET image_url = '/images/paket_pahlawan.png' WHERE name = 'Paket Pahlawan';
UPDATE menu_items SET image_url = '/gambar/paket9.jpeg' WHERE name = 'Suki Grill Besti';
UPDATE menu_items SET image_url = '/gambar/paket10.jpeg' WHERE name = 'Grill Seru Poll – Wisuda';
UPDATE menu_items SET image_url = '/gambar/paket11.jpeg' WHERE name = 'Juliet – Juli Ekstra Hemat';
UPDATE menu_items SET image_url = '/gambar/paket12.jpeg' WHERE name = 'Week N Steak – Pesta Stick';
UPDATE menu_items SET image_url = '/gambar/paket13.jpeg' WHERE name = 'Week N Steak – Pesta Meltique';
UPDATE menu_items SET image_url = '/gambar/paket14.jpeg' WHERE name = 'Paket Bombastis – Tahun Baru';
UPDATE menu_items SET image_url = '/gambar/paket15.jpeg' WHERE name = 'Duo Combo Sweet';
UPDATE menu_items SET image_url = 'https://search.brave.com/images?q=Isa+Gambar&context=W3sic3JjIjoiaHR0cHM6Ly91cGxvYWQud2lraW1lZGlhLm9yZy93aWtpcGVkaWEvY29tbW9ucy90aHVtYi84LzgxLyVDNCVCMHNhX1ElQzklOTltYiVDOSU5OXJfJTI4Y3JvcHBlZCUyOS5qcGcvNTEycHgtJUM0JUIwc2FfUSVDOSU5OW1iJUM5JTk5cl8lMjhjcm9wcG' WHERE name = 'gatau';
UPDATE menu_items SET image_url = 'https://www.astronauts.id/blog/wp-content/uploads/2022/08/Makanan-Khas-Daerah-tiap-Provinsi-di-Indonesia-Serta-Daerah-Asalnya-1024x683.jpg' WHERE name = 'sate';
